/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/dev-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dev Users
         * @description Retorna la lista de usuarios locales para inicio de sesión rápido en desarrollo.
         *     Estrictamente prohibido y deshabilitado (404) en producción.
         */
        get: operations["list_dev_users_api_v1_auth_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Genera un JWT válido para el usuario especificado en entorno de desarrollo.
         *     Si el usuario no existe en la base de datos local, lo aprovisiona automáticamente.
         *     Estrictamente prohibido y deshabilitado (404) en producción.
         */
        post: operations["dev_login_api_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Me
         * @description Obtiene el perfil completo y configuración del usuario autenticado actual.
         */
        get: operations["get_user_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Profile
         * @description Actualiza la información del perfil (nombre y apellido).
         */
        patch: operations["update_user_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export User Data
         * @description Exporta todos los datos personales asociados al usuario (GDPR Art. 15 y 20).
         */
        get: operations["export_user_data_api_v1_users_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User Account
         * @description Suprime la cuenta del usuario cumpliendo con el Derecho al Olvido (GDPR Art. 17).
         *     Valida precondiciones (suscripciones activas, organizaciones), anonimiza el perfil,
         *     preserva las API keys para no romper integraciones de las organizaciones, y encola la baja en el IdP.
         */
        delete: operations["delete_user_account_api_v1_users_me_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Settings
         * @description Obtiene las preferencias de notificación y estado de suscripción del usuario.
         */
        get: operations["get_user_settings_api_v1_users_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Settings
         * @description Actualiza las preferencias de notificaciones.
         */
        patch: operations["update_user_settings_api_v1_users_settings_patch"];
        trace?: never;
    };
    "/api/v1/users/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Trial
         * @description Inicia un período de prueba gratuito de 14 días verificando que no haya sido consumido.
         */
        post: operations["start_trial_api_v1_users_trial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subscription Plans
         * @description Lista todos los planes de suscripción activos disponibles para contratar.
         */
        get: operations["list_subscription_plans_api_v1_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Subscription
         * @description Crea una nueva suscripción en Stripe utilizando un PaymentMethod ID.
         */
        post: operations["create_subscription_api_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription Status
         * @description Obtiene el estado actual de suscripción y facturación del usuario autenticado.
         */
        get: operations["get_subscription_status_api_v1_billing_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Subscription
         * @description Cancela la suscripción al final del ciclo actual para mantener el acceso pagado.
         */
        post: operations["cancel_subscription_api_v1_billing_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Customer Portal
         * @description Genera una URL de sesión temporal del Customer Portal para autogestión de facturación.
         */
        post: operations["create_customer_portal_api_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Procesa eventos webhook asíncronos de Stripe de forma segura e idempotente.
         */
        post: operations["stripe_webhook_api_v1_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Organizations
         * @description Lista organizaciones accesibles.
         *
         *     - JWT: todas las organizaciones del usuario
         *     - API Key: solo la organización de la key
         */
        get: operations["list_user_organizations_api_v1_organizations_get"];
        put?: never;
        /**
         * Create Organization
         * @description Crea una nueva organización (workspace) y asigna al usuario actual como 'owner'.
         */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Workspace
         * @description Obtiene el espacio de trabajo / organización actualmente activo según el header X-Organization-ID.
         */
        get: operations["get_active_workspace_api_v1_organizations_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization
         * @description Obtiene el detalle de la organización si el usuario es miembro.
         */
        get: operations["get_organization_api_v1_organizations__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Organization
         * @description Actualiza los datos básicos de la organización (requiere rol owner o admin).
         */
        patch: operations["update_organization_api_v1_organizations__org_id__patch"];
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organization Members
         * @description Lista todos los miembros de la organización con sus respectivos roles y perfiles.
         */
        get: operations["list_organization_members_api_v1_organizations__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Elimina a un miembro de la organización respetando jerarquías.
         */
        delete: operations["remove_member_api_v1_organizations__org_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Member Role
         * @description Actualiza el rol de un miembro ('admin' o 'member').
         */
        patch: operations["update_member_role_api_v1_organizations__org_id__members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invitations
         * @description Lista todas las invitaciones pendientes de la organización.
         */
        get: operations["list_invitations_api_v1_organizations__org_id__invitations_get"];
        put?: never;
        /**
         * Create Invitation
         * @description Genera una invitación por email con token temporal (7 días de validez).
         */
        post: operations["create_invitation_api_v1_organizations__org_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Invitation
         * @description Revoca una invitación pendiente.
         */
        delete: operations["revoke_invitation_api_v1_organizations__org_id__invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invitation
         * @description Permite al usuario autenticado aceptar una invitación y sumarse a la organización.
         */
        post: operations["accept_invitation_api_v1_organizations_invitations__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description Lista todas las API keys activas y revocadas de la organización.
         *     Oculta el secreto y muestra solo el prefijo seguro (ej: 'sk_test_abc1...').
         */
        get: operations["list_api_keys_api_v1_organizations__org_id__api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Crea una nueva API Key para la organización con scopes restringidos.
         *     Solo accesible por personas (JWT) con rol 'owner' o 'admin'.
         *     El secreto completo se devuelve una única vez y con header Cache-Control: no-store.
         */
        post: operations["create_api_key_api_v1_organizations__org_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Api Key
         * @description Obtiene los detalles de una API key específica de la organización (enmascarando el secreto).
         *     Filtra por organization_id y key_id para prevenir vulnerabilidades IDOR.
         */
        get: operations["get_api_key_api_v1_organizations__org_id__api_keys__key_id__get"];
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Revoca inmediatamente una API key de la organización.
         *     Cualquier petición subsiguiente con esta key retornará 401 Unauthorized.
         */
        delete: operations["revoke_api_key_api_v1_organizations__org_id__api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization Usage
         * @description Retorna el resumen consolidado de cuotas y uso de la organización en su período vigente.
         *     Accesible por miembros de la organización (JWT) o mediante API Key con scope 'members:read'.
         */
        get: operations["get_organization_usage_api_v1_organizations__org_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Endpoint de chat con IA en streaming (SSE: text/event-stream).
         *     - Soporta autenticación dual: JWT (miembros de la org) y API Key (con scope 'ai:generate').
         *     - Valida cuota de uso mensual ('ai_messages') atómicamente antes de abrir la conexión (D-08).
         *     - Si la cuota está agotada, responde con HTTP 402 Payment Required y payload estructurado (D-04).
         *     - Emite eventos estándar: 'meta', 'delta', 'usage', 'done' y keepalives ': ping'.
         *     - Si el proveedor falla antes del primer token, reembolsa automáticamente el uso (D-08).
         *     - Registra auditoría inmutable de consumo sin persistir datos sensibles (D-03).
         */
        post: operations["chat_stream_api_v1_ai_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Email Templates
         * @description Galería interactiva para previsualizar todas las plantillas de correo en desarrollo.
         */
        get: operations["list_email_templates_dev_emails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/emails/preview/{template_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Email
         * @description Renderiza una plantilla de correo específica con datos de prueba.
         */
        get: operations["preview_email_dev_emails_preview__template_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Endpoint de verificación de estado (Health Check) para monitoreo y contenedores.
         *     Verifica activamente la conectividad con la base de datos ejecutando SELECT 1.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Endpoint raíz con información general y enlaces a la documentación interactiva.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountDeletionResponse
         * @description Confirmación de supresión y anonimización de cuenta bajo GDPR (Derecho al Olvido).
         */
        AccountDeletionResponse: {
            /**
             * Message
             * @default Tu cuenta y datos personales han sido anonimizados de acuerdo a GDPR.
             */
            message: string;
            /**
             * Status
             * @default anonymized
             */
            status: string;
            /**
             * Deleted At
             * Format: date-time
             */
            deleted_at: string;
        };
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /**
             * Name
             * @description Nombre o etiqueta descriptiva (ej: 'Zapier Integration')
             */
            name: string;
            /**
             * Scopes
             * @description Lista de permisos asignados a la key
             */
            scopes: components["schemas"]["Scope"][];
            /**
             * Expires In Days
             * @description Días hasta expiración (opcional)
             */
            expires_in_days?: number | null;
        };
        /** ApiKeyCreatedResponse */
        ApiKeyCreatedResponse: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Created By Id */
            created_by_id?: number | null;
            /** Expires At */
            expires_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Raw Key
             * @description Secreto completo. Solo se muestra una vez al crearse.
             */
            raw_key: string;
            /**
             * Message
             * @default Copia esta clave ahora. Por motivos de seguridad, no se volverá a mostrar.
             */
            message: string;
        };
        /** ApiKeyRead */
        ApiKeyRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Created By Id */
            created_by_id?: number | null;
            /** Expires At */
            expires_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ChatMessage
         * @description Mensaje individual en una conversación de chat.
         */
        ChatMessage: {
            /**
             * Role
             * @description Rol del autor del mensaje ('system', 'user', o 'assistant')
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /**
             * Content
             * @description Contenido del mensaje
             */
            content: string;
        };
        /**
         * ChatStreamRequest
         * @description Cuerpo de la solicitud para el endpoint POST /ai/chat/stream.
         */
        ChatStreamRequest: {
            /**
             * Messages
             * @description Historial de mensajes de la conversación. El último debe ser del rol 'user'.
             */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Model
             * @description Modelo de IA solicitado. Debe estar en la lista blanca permitida por el backend.
             */
            model?: string | null;
            /**
             * Temperature
             * @description Parámetro de aleatoriedad en la respuesta (0.0 a 2.0).
             * @default 0.7
             */
            temperature: number | null;
            /**
             * Max Output Tokens
             * @description Número máximo de tokens generados en la respuesta.
             */
            max_output_tokens?: number | null;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Payment Method Id */
            payment_method_id: string;
            /** Price Id */
            price_id?: string | null;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Subscription Id */
            subscription_id: string;
            /** Client Secret */
            client_secret?: string | null;
            /** Requires Confirmation */
            requires_confirmation: boolean;
            /** Status */
            status: string;
        };
        /** CustomerPortalRequest */
        CustomerPortalRequest: {
            /** Return Url */
            return_url?: string | null;
        };
        /** CustomerPortalResponse */
        CustomerPortalResponse: {
            /** Url */
            url: string;
        };
        /** DevLoginRequest */
        DevLoginRequest: {
            /** Email */
            email: string;
        };
        /** DevLoginResponse */
        DevLoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["DevUserRead"];
        };
        /** DevUserOrg */
        DevUserOrg: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Role */
            role: string;
        };
        /** DevUserRead */
        DevUserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Cognito Sub */
            cognito_sub: string;
            /** Organizations */
            organizations: components["schemas"]["DevUserOrg"][];
        };
        /** ExportAiUsageEvent */
        ExportAiUsageEvent: {
            /** Request Id */
            request_id: string;
            /** Organization Id */
            organization_id: number;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Status */
            status: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExportApiKey */
        ExportApiKey: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /** ExportOrganizationMembership */
        ExportOrganizationMembership: {
            /** Organization Id */
            organization_id: number;
            /** Organization Name */
            organization_name: string;
            /** Organization Slug */
            organization_slug: string;
            /** Role */
            role: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** ExportStripeCustomer */
        ExportStripeCustomer: {
            /** Stripe Customer Id */
            stripe_customer_id: string;
            /** Subscription Status */
            subscription_status?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
        };
        /** ExportUserProfile */
        ExportUserProfile: {
            /** Id */
            id: number;
            /** Cognito Sub */
            cognito_sub: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExportUserSettings */
        ExportUserSettings: {
            /** Subscription Status */
            subscription_status: string;
            /** Subscription Start Date */
            subscription_start_date?: string | null;
            /** Subscription End Date */
            subscription_end_date?: string | null;
            /**
             * Notify Comments
             * @default false
             */
            notify_comments: boolean;
            /**
             * Notify Updates
             * @default false
             */
            notify_updates: boolean;
            /**
             * Notify Marketing
             * @default false
             */
            notify_marketing: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationAcceptResponse */
        InvitationAcceptResponse: {
            /** Message */
            message: string;
            /** Organization Id */
            organization_id: number;
            /** Role */
            role: string;
        };
        /** InvitationCreate */
        InvitationCreate: {
            /**
             * Email
             * Format: email
             * @description Correo del nuevo miembro a invitar
             */
            email: string;
            /**
             * Role
             * @description Rol que tendrá en la organización
             * @default member
             */
            role: string;
        };
        /** InvitationRead */
        InvitationRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Token */
            token: string;
            /** Status */
            status: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /**
             * Name
             * @description Nombre de la organización
             */
            name: string;
            /**
             * Slug
             * @description Identificador único legible en URL
             */
            slug?: string | null;
        };
        /** OrganizationMemberRead */
        OrganizationMemberRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** User Id */
            user_id: number;
            /** Role */
            role: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrganizationMemberUpdateRole */
        OrganizationMemberUpdateRole: {
            /**
             * Role
             * @description Nuevo rol para el miembro ('admin' o 'member')
             */
            role: string;
        };
        /** OrganizationRead */
        OrganizationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Owner Id */
            owner_id: number;
            /** Subscription Status */
            subscription_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /**
         * Scope
         * @description Permisos que puede tener una API Key. Formato ``recurso:acción``.
         *
         *     No existe un scope ``admin`` a propósito: una key no puede administrar
         *     keys (crear, listar, modificar o revocar). Eso es solo para JWT, así una
         *     key con permisos limitados no puede escalarse a sí misma.
         * @enum {string}
         */
        Scope: "users:read" | "users:write" | "members:read" | "members:write" | "billing:read" | "billing:write" | "ai:generate";
        /** SubscriptionPlanRead */
        SubscriptionPlanRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Price */
            price: string;
            /** Interval */
            interval: string;
            /** Features */
            features: unknown[];
            /** Is Active */
            is_active: boolean;
        };
        /** SubscriptionStatusResponse */
        SubscriptionStatusResponse: {
            /** Status */
            status: string;
            /** Is Active */
            is_active: boolean;
            /** Is Trial */
            is_trial: boolean;
            /** Current Period End */
            current_period_end?: string | null;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id?: string | null;
        };
        /**
         * UsageMetricStatus
         * @description Estado de consumo de una métrica individual.
         */
        UsageMetricStatus: {
            /**
             * Metric
             * @description Nombre de la métrica (ej: 'ai_messages', 'members')
             */
            metric: string;
            /**
             * Used
             * @description Cantidad utilizada en el período actual
             */
            used: number;
            /**
             * Limit
             * @description Límite máximo permitido. None = ilimitado
             */
            limit?: number | null;
            /**
             * Remaining
             * @description Cantidad restante. None si es ilimitado
             */
            remaining?: number | null;
        };
        /**
         * UsageSummary
         * @description Resumen consolidado de uso para la organización en su período de facturación.
         */
        UsageSummary: {
            /**
             * Organization Id
             * @description ID de la organización
             */
            organization_id: number;
            /**
             * Period Start
             * Format: date-time
             * @description Inicio del período de facturación (UTC)
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             * @description Fin del período de facturación (UTC)
             */
            period_end: string;
            /**
             * Metrics
             * @description Métricas evaluadas
             */
            metrics: components["schemas"]["UsageMetricStatus"][];
        };
        /**
         * UserDataExport
         * @description Estructura completa de exportación de datos del usuario bajo GDPR (Derecho de Acceso y Portabilidad).
         */
        UserDataExport: {
            user: components["schemas"]["ExportUserProfile"];
            settings?: components["schemas"]["ExportUserSettings"] | null;
            /** Memberships */
            memberships?: components["schemas"]["ExportOrganizationMembership"][];
            stripe_customer?: components["schemas"]["ExportStripeCustomer"] | null;
            /** Created Api Keys */
            created_api_keys?: components["schemas"]["ExportApiKey"][];
            /** Ai Usage Events */
            ai_usage_events?: components["schemas"]["ExportAiUsageEvent"][];
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
        };
        /** UserMeResponse */
        UserMeResponse: {
            profile: components["schemas"]["UserProfileRead"];
            settings?: components["schemas"]["UserSettingsRead"] | null;
        };
        /** UserProfileRead */
        UserProfileRead: {
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /** Id */
            id: number;
            /** Cognito Sub */
            cognito_sub: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
        };
        /** UserSettingsRead */
        UserSettingsRead: {
            /**
             * Notify Comments
             * @default false
             */
            notify_comments: boolean;
            /**
             * Notify Updates
             * @default false
             */
            notify_updates: boolean;
            /**
             * Notify Marketing
             * @default false
             */
            notify_marketing: boolean;
            /** Subscription Status */
            subscription_status: string;
            /** Subscription Start Date */
            subscription_start_date?: string | null;
            /** Subscription End Date */
            subscription_end_date?: string | null;
            /** Trial End Date */
            trial_end_date?: string | null;
            /** Is Subscription Active */
            is_subscription_active: boolean;
            /** Is Trial Active */
            is_trial_active: boolean;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            /**
             * Notify Comments
             * @default false
             */
            notify_comments: boolean;
            /**
             * Notify Updates
             * @default false
             */
            notify_updates: boolean;
            /**
             * Notify Marketing
             * @default false
             */
            notify_marketing: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dev_users_api_v1_auth_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUserRead"][];
                };
            };
        };
    };
    dev_login_api_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    update_user_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_user_data_api_v1_users_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataExport"];
                };
            };
        };
    };
    delete_user_account_api_v1_users_me_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionResponse"];
                };
            };
        };
    };
    get_user_settings_api_v1_users_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsRead"];
                };
            };
        };
    };
    update_user_settings_api_v1_users_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_trial_api_v1_users_trial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_subscription_plans_api_v1_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlanRead"][];
                };
            };
        };
    };
    create_subscription_api_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_status_api_v1_billing_subscription_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusResponse"];
                };
            };
        };
    };
    cancel_subscription_api_v1_billing_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_customer_portal_api_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPortalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_v1_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "stripe-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"][];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_workspace_api_v1_organizations_active_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Organization-ID"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_api_v1_organizations__org_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organization_members_api_v1_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_organizations__org_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_v1_organizations__org_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationMemberUpdateRole"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invitations_api_v1_organizations__org_id__invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_organizations__org_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_organizations__org_id__invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
                invitation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_organizations_invitations__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_organizations__org_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_api_v1_organizations__org_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_key_api_v1_organizations__org_id__api_keys__key_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_organizations__org_id__api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_usage_api_v1_organizations__org_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_ai_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_email_templates_dev_emails_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    preview_email_dev_emails_preview__template_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
